### PR TITLE
Removed duplicate code in conditions.ts, added documentations, and added types

### PR DESCRIPTION
**Pull request by BergerAPI**
I hope I didn't overdo the docs

### CODE REVIEW

**Comment by BergerAPI** [comment]
Oops, I just noticed that this interferes with the database-wrappers, since you named some parameters a, and some values b. My friend is already working on updating the wrappers, and therefore will fix this.

**Comment by William-McGonagle** [comment]
I really like the implementation that you did on the conditions file- that's going to be fast. Are the changes ready to merge?

**Comment by BergerAPI** [comment]
> I really like the implementation that you did on the conditions file- that's going to be fast. Are the changes ready to merge?

In both the implementations of the conditions for each database-wrapper (e.g. `src/databases/sql/condition.ts`) the as need to be replaces by `parameter` and the bs is `value`.

image

**Comment by BergerAPI** [comment]
Should I commit the fix this or do you want to fix it in your next commit? @William-McGonagle

**Comment by William-McGonagle** [comment]
You can just fix it in the next commit if it's easier @BergerAPI

**Comment by BergerAPI** [comment]
@William-McGonagle Ready to merge. I've also changed the ifs in the wrapper-implementations to a switch case.

Working as intended:

image

**Comment by William-McGonagle** [comment]
Looks good- merging it in now!

**Pull request merged**
