### PR TITLE
Documentation Website

### PR DESCRIPTION
**Pull request by adetyaz**
-First page for the website is completed.
-Actions created for deployment in .github/workflows folder

### CODE REVIEW

**Comment by William-McGonagle** [comment]
Looks good!

**Comment by William-McGonagle** [comment]
Hey @adetyaz, can you move the docs folder and rename it to the website and then set the build folder for the website to be the docs folder.

**Comment by William-McGonagle** [comment]
Nevermind actually- the website seems to be working!

**Comment by adetyaz** [comment]
did you make any changes to the website colors  and fonts for the logo?

**Pull request merged**
